const VERSION="20260705-v2-boykotta-degil";
let DATA=[]; let view="home"; let filter="all"; let favorites=loadFavorites(); let currentTitle="Tüm Markalar";
const $=id=>document.getElementById(id); const search=$("search"), clearBtn=$("clearBtn"), stats=$("stats"), quickFilters=$("quickFilters"), sectionTitle=$("sectionTitle"), results=$("results"), themeBtn=$("themeBtn");
function esc(s){return String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function norm(s){return String(s||"").toLocaleLowerCase("tr-TR").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[’'`´]/g,"").replace(/[^a-z0-9ğüşöçıİĞÜŞÖÇ]+/gi," ").trim()}
function get(o,names){for(const n of names){if(o&&o[n]!==undefined&&o[n]!==null&&String(o[n]).trim()!=="")return String(o[n]).trim()}return""}
function loadFavorites(){try{return JSON.parse(localStorage.getItem("boykot_favorites_v3")||"[]")}catch{return[]}}
function saveFavorites(){localStorage.setItem("boykot_favorites_v3",JSON.stringify(favorites))}
function favKey(m){return norm(m)} function isFav(m){return favorites.includes(favKey(m))} function toggleFav(m){const k=favKey(m); favorites=isFav(m)?favorites.filter(x=>x!==k):[...favorites,k]; saveFavorites(); render()}
function rawStatus(r,kod){const d=norm(get(r,["durum","Durum","status"])); if(d.includes("boykottadegil")||d.includes("boykotta degil")||d==="safe")return"safe"; if(d.includes("alternatif"))return"alternatif"; if(d.includes("dikkat"))return"dikkat"; if(d.includes("incelen"))return"inceleme"; if(/^E/i.test(kod))return"safe"; if(/^C/i.test(kod))return"alternatif"; if(/^B/i.test(kod))return"dikkat"; if(/^D/i.test(kod))return"inceleme"; return"boykot"}
const statusLabel={boykot:"🔴 Boykot",dikkat:"🟠 Dikkat",alternatif:"🟢 Alternatif",safe:"✅ Boykotta Değil",inceleme:"⚪ İnceleniyor"};
function hasAlternative(x){const a=norm(x.alternatif);return !!a&&!a.includes("alternatif manuel eklenmeli")}
function normalizeItem(raw,i){const marka=get(raw,["marka","Marka","brand"])||`Marka ${i+1}`; const anaFirma=get(raw,["anaFirma","anafirma","Ana Firma","AnaFirma","ana_firma"])||marka; const kod=get(raw,["kod","Kod","code"])||"D1"; const kategori=get(raw,["kategori","Kategori","category"]); const alternatif=get(raw,["alternatif","Alternatif","alternative"]); const kaynak=get(raw,["kaynak","Kaynak","kanyak","source","link"]); const not=get(raw,["not","Not","note"]); const status=rawStatus(raw,kod); const hay=norm([marka,anaFirma,kod,kategori,alternatif,kaynak,not,statusLabel[status]].join(" ")); return{marka,anaFirma,kod,kategori,alternatif,kaynak,not,status,hay}}
async function clearOldCaches(){try{if("caches" in window){const keys=await caches.keys();await Promise.all(keys.map(k=>caches.delete(k)))}}catch(e){}}
async function init(){applyTheme(); await clearOldCaches(); try{const res=await fetch(`data.json?v=${VERSION}`,{cache:"reload"}); if(!res.ok)throw new Error(`data.json yüklenemedi: ${res.status}`); const json=await res.json(); const list=Array.isArray(json)?json:(Array.isArray(json.data)?json.data:[]); DATA=list.map(normalizeItem).sort((a,b)=>a.marka.localeCompare(b.marka,"tr")); render()}catch(err){stats.innerHTML="";quickFilters.innerHTML="";sectionTitle.innerHTML="";results.innerHTML=`<div class="empty"><b>Veri yüklenemedi.</b><br>${esc(err.message)}<br><br>data.json dosyası index.html ile aynı klasörde olmalı.</div>`}}
function counts(){return{total:DATA.length,boykot:DATA.filter(x=>x.status==="boykot").length,dikkat:DATA.filter(x=>x.status==="dikkat").length,alternatif:DATA.filter(x=>x.status==="alternatif").length,safe:DATA.filter(x=>x.status==="safe").length,inceleme:DATA.filter(x=>x.status==="inceleme").length,altli:DATA.filter(hasAlternative).length,firmalar:new Set(DATA.map(x=>x.anaFirma||"Belirtilmemiş")).size}}
function renderStats(){const c=counts(); stats.innerHTML=`<div class="stat"><b>${c.total}</b><small>Toplam</small></div><div class="stat red"><b>${c.boykot}</b><small>Boykot</small></div><div class="stat safe"><b>${c.safe}</b><small>Boykotta Değil</small></div><div class="stat green"><b>${c.altli}</b><small>Alternatifli</small></div><div class="stat gray"><b>${c.inceleme}</b><small>İnceleniyor</small></div>`}
function renderFilters(){const arr=[["all","Tümü"],["boykot","🔴 Boykot"],["safe","✅ Boykotta Değil"],["altli","🟢 Alternatifli"],["inceleme","⚪ İnceleniyor"],["fav","⭐ Favoriler"]]; quickFilters.innerHTML=arr.map(([k,l])=>`<button class="chip ${filter===k?'active':''}" data-filter="${k}" type="button">${l}</button>`).join("")}
function filteredList(base=DATA){const q=norm(search.value);return base.filter(x=>{const okQ=!q||x.hay.includes(q); const okF=filter==="all"||(filter==="boykot"&&x.status==="boykot")||(filter==="safe"&&x.status==="safe")||(filter==="altli"&&hasAlternative(x))||(filter==="inceleme"&&x.status==="inceleme")||(filter==="fav"&&isFav(x.marka)); return okQ&&okF}).sort((a,b)=>isFav(b.marka)-isFav(a.marka)||a.marka.localeCompare(b.marka,"tr"))}
function badge(x){return`<span class="badge ${x.status}">${statusLabel[x.status]||"Kod"} <b>${esc(x.kod||"")}</b></span>`}
function tagHtml(alt,status){if(status==="safe"&&!alt)return`<div class="box alt"><span>Durum</span><b>Bu marka boykot listesinde olmayanlar bölümüne eklendi.</b></div>`; if(!hasAlternative({alternatif:alt}))return`<div class="box alt"><span>Alternatif</span><b>-</b></div>`; const tags=alt.split(/[;,•]/).map(x=>x.trim()).filter(Boolean).slice(0,9); return`<div class="box alt"><span>Alternatif</span><div class="tags">${tags.map(t=>`<em>${esc(t)}</em>`).join("")}</div></div>`}
function card(x){return`<article class="card ${x.status}" data-brand="${encodeURIComponent(x.marka)}"><div class="cardTop"><div><div class="badgeLine">${badge(x)}${hasAlternative(x)?'<span class="badge alternatif">🟢 Alternatif var</span>':''}</div><h3>${esc(x.marka)}</h3><div class="company">🏢 ${esc(x.anaFirma||"Belirtilmemiş")}</div></div><button class="fav" data-fav="${encodeURIComponent(x.marka)}" type="button">${isFav(x.marka)?"★":"☆"}</button></div><div class="meta"><div class="box"><span>Kategori</span><b>${esc(x.kategori||"Belirtilmemiş")}</b></div><div class="box"><span>Kod</span><b>${esc(x.kod||"-")}</b></div></div>${tagHtml(x.alternatif,x.status)}<button class="more" type="button">Ayrıntıları Gör →</button></article>`}
function renderHome(list=filteredList(),title=currentTitle){renderStats();renderFilters();sectionTitle.innerHTML=`<h2>${esc(title)}</h2><span>${list.length} sonuç</span>`;results.innerHTML=list.length?list.slice(0,700).map(card).join("")+(list.length>700?'<div class="empty">İlk 700 sonuç gösteriliyor. Daha dar arama yap.</div>':""):'<div class="empty">Sonuç bulunamadı.</div>'}
function groupBy(key,base=DATA){const m=new Map();for(const x of base){const name=x[key]||"Belirtilmemiş";if(!m.has(name))m.set(name,[]);m.get(name).push(x)}return[...m.entries()].sort((a,b)=>b[1].length-a[1].length||a[0].localeCompare(b[0],"tr"))}
function renderGroups(key,title,attr,base=DATA){renderStats();quickFilters.innerHTML="";search.value="";const g=groupBy(key,base);sectionTitle.innerHTML=`<h2>${title}</h2><span>${g.length} liste</span>`;results.innerHTML=g.map(([name,items])=>`<div class="group" ${attr}="${encodeURIComponent(name)}"><div><b>${esc(name)}</b><br><small>${items.slice(0,4).map(x=>esc(x.marka)).join(", ")}${items.length>4?"...":""}</small></div><div class="count">${items.length}</div></div>`).join("")}
function renderAbout(){const c=counts();stats.innerHTML="";quickFilters.innerHTML="";sectionTitle.innerHTML="";search.value="";results.innerHTML=`<section class="aboutHero"><h2>📖 Boykot Rehberi</h2><p>Markaları, ana firmaları, kategorileri ve alternatifleri hızlıca bulmak için hazırlanmış mobil uyumlu rehber.</p></section><div class="aboutGrid"><div class="aboutCard"><h3>📊 Liste Durumu</h3><p><b>${c.total}</b> toplam kayıt var. Bunların <b>${c.boykot}</b> tanesi boykot, <b>${c.safe}</b> tanesi boykotta değil bölümünde, <b>${c.altli}</b> tanesinde alternatif bilgisi var.</p></div><div class="aboutCard"><h3>✅ Boykotta Değil</h3><p>Bu bölüm, eklenen alternatif listesinden gelen ve ana boykot listesinde bulunmayan markaları gösterir.</p></div><div class="aboutCard"><h3>🔍 Nasıl Aranır?</h3><p>Arama kutusuna marka adı, ana firma, kategori veya alternatif ürün yazabilirsin. Örneğin: P&G, Temizlik, Peros.</p></div><div class="aboutCard"><h3>🏢 Ana Firmalar</h3><p>Aynı şirkete ait markaları görmek için alt menüden Firmalar bölümünü aç.</p></div><div class="aboutCard"><h3>⭐ Favoriler</h3><p>Yıldız işaretine basarak markaları favorilere ekleyebilir, sonra filtrelerden Favoriler bölümünden bulabilirsin.</p></div><div class="aboutCard"><h3>🟢 Alternatifler</h3><p>Alternatif olarak gösterilen ürünler aynı ürün grubunda değerlendirilebilecek seçeneklerdir. Satın almadan önce kendi araştırmanı yapman tavsiye edilir.</p></div><div class="aboutCard"><h3>⚠️ Bilgilendirme</h3><p>Bu uygulama yalnızca bilgilendirme amacıyla hazırlanmıştır. Bilgiler farklı kaynaklardan derlenmiştir ve zamanla değişebilir. Güncel bilgileri bağımsız kaynaklardan doğrulamanız önerilir.</p></div><div class="aboutCard"><h3>🔄 Güncelleme</h3><p>Yeni marka eklemek veya bilgileri değiştirmek için data.json dosyasını güncellemen yeterlidir.</p></div></div>`}
function render(){document.querySelectorAll(".bottomNav button").forEach(b=>b.classList.toggle("active",b.dataset.view===view)); if(view==="home")return renderHome(); if(view==="boykot"){filter="boykot";currentTitle="🔴 Boykot Listesi";return renderHome(filteredList(),currentTitle)} if(view==="safe"){filter="safe";currentTitle="✅ Boykotta Değil";return renderHome(filteredList(),currentTitle)} if(view==="companies")return renderGroups("anaFirma","🏢 Ana Firmalar","data-company"); if(view==="about")return renderAbout()}
function detail(x){const d=$("detailDialog"), c=$("detailContent");c.innerHTML=`<div class="detailHead"><h2>${esc(x.marka)}</h2><p>${esc(x.anaFirma||"Belirtilmemiş")}</p></div><div class="detailBody"><div class="detailLine"><span>Durum</span><b>${statusLabel[x.status]||"-"}</b></div><div class="detailLine"><span>Ana Firma</span><b>${esc(x.anaFirma||"Belirtilmemiş")}</b></div><div class="detailLine"><span>Kategori</span><b>${esc(x.kategori||"Belirtilmemiş")}</b></div><div class="detailLine"><span>Kod</span><b>${esc(x.kod||"-")}</b></div><div class="detailLine"><span>Alternatif</span><b>${esc(x.alternatif||"-")}</b></div><div class="detailLine"><span>Not</span><b>${esc(x.not||"-")}</b></div><div class="detailLine"><span>Kaynak</span><b>${/^https?:\/\//.test(x.kaynak)?`<a href="${esc(x.kaynak)}" target="_blank" rel="noopener">Kaynağı aç</a>`:esc(x.kaynak||"-")}</b></div></div>`;d.showModal()}
search.addEventListener("input",()=>{view="home";filter="all";currentTitle="Arama Sonuçları";render()}); clearBtn.addEventListener("click",()=>{search.value="";filter="all";view="home";currentTitle="Tüm Markalar";render()}); quickFilters.addEventListener("click",e=>{const b=e.target.closest("[data-filter]");if(!b)return;filter=b.dataset.filter;view="home";currentTitle=b.textContent.trim();render()}); document.querySelectorAll(".bottomNav button").forEach(b=>b.addEventListener("click",()=>{view=b.dataset.view; if(view==="home"){filter="all";currentTitle="Tüm Markalar"} render()})); results.addEventListener("click",e=>{const fav=e.target.closest("[data-fav]");if(fav){e.stopPropagation();toggleFav(decodeURIComponent(fav.dataset.fav));return}const card=e.target.closest("[data-brand]");if(card){const item=DATA.find(x=>x.marka===decodeURIComponent(card.dataset.brand));if(item)detail(item);return}const comp=e.target.closest("[data-company]");if(comp){const name=decodeURIComponent(comp.dataset.company);search.value=name;view="home";filter="all";currentTitle=`🏢 ${name}`;render()}}); $("closeDialog").addEventListener("click",()=>$("detailDialog").close()); themeBtn.addEventListener("click",()=>{document.body.classList.toggle("dark");localStorage.setItem("boykot_theme",document.body.classList.contains("dark")?"dark":"light");themeBtn.textContent=document.body.classList.contains("dark")?"☀️":"🌙"}); function applyTheme(){const t=localStorage.getItem("boykot_theme");if(t==="dark")document.body.classList.add("dark");themeBtn.textContent=document.body.classList.contains("dark")?"☀️":"🌙"}
if("serviceWorker" in navigator){navigator.serviceWorker.getRegistrations().then(rs=>Promise.all(rs.map(r=>r.unregister()))).catch(()=>{});navigator.serviceWorker.register("sw.js?v="+VERSION).catch(()=>{})} init();
