-- Ahlak Rehberim V27 Supabase tablo şablonu
-- Supabase SQL Editor içinde çalıştırılabilir.

create table if not exists public.brands (
  id bigint generated by default as identity primary key,
  marka text not null,
  ana_firma text,
  kategori text,
  ulke text,
  durum text default 'inceleme',
  image_url text,
  notlar text,
  ozet text,
  kaynaklar jsonb default '[]'::jsonb,
  alternatifler jsonb default '[]'::jsonb,
  barkodlar jsonb default '[]'::jsonb,
  son_guncelleme date,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists brands_marka_idx on public.brands using gin (to_tsvector('simple', coalesce(marka,'')));
create index if not exists brands_durum_idx on public.brands (durum);
create index if not exists brands_kategori_idx on public.brands (kategori);
create index if not exists brands_ulke_idx on public.brands (ulke);

alter table public.brands enable row level security;

-- Okuma herkese açık olabilir:
drop policy if exists "public read brands" on public.brands;
create policy "public read brands"
on public.brands for select
to anon, authenticated
using (true);

-- Yazma için başlangıçta anon kapalı tutmak daha güvenlidir.
-- Admin yazma için Supabase Auth ile authenticated kullanıcıya izin verilebilir:
drop policy if exists "authenticated insert brands" on public.brands;
create policy "authenticated insert brands"
on public.brands for insert
to authenticated
with check (true);

drop policy if exists "authenticated update brands" on public.brands;
create policy "authenticated update brands"
on public.brands for update
to authenticated
using (true)
with check (true);
