-- Ahlak Rehberim V33 öneri/moderasyon tablosu

create table if not exists public.suggestions (
  id bigint generated by default as identity primary key,
  tur text not null,
  marka text,
  ana_firma text,
  url text,
  aciklama text,
  durum text default 'bekliyor',
  editor_notu text,
  created_at timestamptz default now(),
  reviewed_at timestamptz
);

create index if not exists suggestions_durum_idx on public.suggestions (durum);
create index if not exists suggestions_marka_idx on public.suggestions (marka);

alter table public.suggestions enable row level security;

-- Öneri göndermek isteyen herkes insert yapabilir.
-- Not: kötüye kullanım olursa captcha / auth eklenmelidir.
drop policy if exists "public insert suggestions" on public.suggestions;
create policy "public insert suggestions"
on public.suggestions for insert
to anon, authenticated
with check (true);

-- Önerileri okumayı herkese açmak önerilmez.
-- Sadece authenticated kullanıcılar okuyabilir:
drop policy if exists "authenticated read suggestions" on public.suggestions;
create policy "authenticated read suggestions"
on public.suggestions for select
to authenticated
using (true);

drop policy if exists "authenticated update suggestions" on public.suggestions;
create policy "authenticated update suggestions"
on public.suggestions for update
to authenticated
using (true)
with check (true);
